/**
 * Real Achterhoek businesses and vouchers for seeding.
 * Data sourced from web research (March 2026) — real names, addresses, pricing.
 */

export interface SeedBusiness {
  email: string
  ownerName: string
  name: string
  description: string
  address: string
  city: string
  postalCode: string
  province: string
  phone: string
  website: string
  categories: string[] // category slugs
  vouchers: SeedVoucher[]
}

export interface SeedVoucher {
  title: string
  description: string
  discountType: 'CASH' | 'PERCENTAGE' | 'PRODUCT' | 'SERVICE'
  discountValue?: number
  discountDescription?: string
  terms: string
  minimumPurchase?: number
  maxClaims: number
  daysValid: number
  slug: string
}

// ─── RESTAURANTS ────────────────────────────────────────────

const restaurants: SeedBusiness[] = [
  {
    email: 'info@kronenhuis.nl',
    ownerName: 'Henk Kronenborg',
    name: 'Restaurant Kronenhuis',
    description: 'Culinair restaurant in het hart van Winterswijk, gevestigd sinds 1927. Gevarieerd menu met klassieke en eigentijdse gerechten, bereid met verse seizoensingrediënten uit de Achterhoek.',
    address: 'Markt 23',
    city: 'Winterswijk',
    postalCode: '7101 DA',
    province: 'Gelderland',
    phone: '0543 512 250',
    website: 'https://www.kronenhuis.nl',
    categories: ['restaurants'],
    vouchers: [
      {
        title: 'High Wine voor twee — €10 korting',
        description: 'Geniet samen van ons 5-gangen High Wine menu (wo/do/zo) voor €85 i.p.v. €95.',
        discountType: 'CASH',
        discountValue: 10,
        terms: 'Geldig op woensdag, donderdag en zondag. Reserveren verplicht. Niet te combineren met andere acties.',
        minimumPurchase: 85,
        maxClaims: 40,
        daysValid: 90,
        slug: 'high-wine-korting-kronenhuis',
      },
      {
        title: 'Gratis amuse bij 3-gangen dinermenu',
        description: 'Ontvang een gratis amuse bij elk 3-gangen menu. Een perfecte start van uw avond.',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis amuse (t.w.v. €8,50)',
        terms: 'Geldig bij het 3-gangen dinermenu. Reserveren verplicht.',
        maxClaims: 60,
        daysValid: 90,
        slug: 'gratis-amuse-kronenhuis',
      },
      {
        title: '€5 korting op lunch voor 2',
        description: 'Lunchen met z\'n tweeën? Ontvang €5 korting op de totaalrekening vanaf €30.',
        discountType: 'CASH',
        discountValue: 5,
        terms: 'Geldig op de lunchkaart bij besteding van minimaal €30. Ma t/m vr.',
        minimumPurchase: 30,
        maxClaims: 70,
        daysValid: 60,
        slug: 'lunch-korting-kronenhuis',
      },
    ],
  },
  {
    email: 'info@hetraedthuys.nl',
    ownerName: 'Peter Vermeulen',
    name: "Eterij en Tapperij 't Raedthuys",
    description: 'Bib Gourmand restaurant aan de Raadhuisstraat in Doetinchem. Culinair genieten in een warme ambiance met seizoensgebonden gerechten en een uitgebreide wijnkaart.',
    address: 'Raadhuisstraat 14',
    city: 'Doetinchem',
    postalCode: '7001 EW',
    province: 'Gelderland',
    phone: '0314 360 704',
    website: 'https://hetraedthuys.nl',
    categories: ['restaurants'],
    vouchers: [
      {
        title: '€15 korting op het 3-gangen Share Menu',
        description: 'Geniet woensdag of donderdag van ons Share Menu voor €30 i.p.v. €45 p.p.',
        discountType: 'CASH',
        discountValue: 15,
        terms: 'Geldig op woensdag en donderdag. Reserveren verplicht via de website.',
        minimumPurchase: 30,
        maxClaims: 30,
        daysValid: 60,
        slug: 'share-menu-korting-raedthuys',
      },
      {
        title: 'Gratis prosecco bij Lazy Sunday menu',
        description: 'Ontvang een gratis glas prosecco bij het Lazy Sunday Signatuur Bites menu (€40 p.p.).',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis glas prosecco (t.w.v. €7,50)',
        terms: 'Geldig op zondag. Reserveren verplicht.',
        maxClaims: 50,
        daysValid: 90,
        slug: 'gratis-prosecco-raedthuys',
      },
      {
        title: '€10 korting op wijnmenu',
        description: 'Kies het bijpassende wijnmenu bij uw diner en ontvang €10 korting.',
        discountType: 'CASH',
        discountValue: 10,
        terms: 'Geldig bij het wijnmenu (4 wijnen). Reserveren verplicht.',
        maxClaims: 35,
        daysValid: 90,
        slug: 'wijnmenu-korting-raedthuys',
      },
    ],
  },
  {
    email: 'info@welgelegengroenlo.nl',
    ownerName: 'Karin Berendsen',
    name: 'Restaurant Welgelegen',
    description: 'Sfeervol restaurant in een monumentaal pand uit 1890 in Groenlo. Uitgebreide lunch- en dinerkaart met klassiekers en seizoensgerechten uit de Achterhoek.',
    address: 'Beltrumsestraat 1',
    city: 'Groenlo',
    postalCode: '7141 AJ',
    province: 'Gelderland',
    phone: '0544 461 247',
    website: 'https://www.welgelegengroenlo.nl',
    categories: ['restaurants'],
    vouchers: [
      {
        title: 'Vriendendiner: 2e persoon halve prijs',
        description: 'Boek het Vriendendiner (4 gangen, €34,95 p.p.) en ontvang 50% korting voor de 2e gast.',
        discountType: 'PERCENTAGE',
        discountValue: 50,
        terms: 'Geldig op het 4-gangen Vriendendiner. Korting geldt voor de 2e persoon. Reserveren verplicht.',
        minimumPurchase: 35,
        maxClaims: 40,
        daysValid: 90,
        slug: 'vriendendiner-welgelegen',
      },
      {
        title: 'Gratis dessert bij elke lunch',
        description: 'Ontvang een gratis dessert bij besteding van minimaal €20 op de lunchkaart.',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis dessert (t.w.v. €8,50)',
        terms: 'Geldig bij een lunchbesteding van minimaal €20. Niet te combineren met andere acties.',
        minimumPurchase: 20,
        maxClaims: 80,
        daysValid: 60,
        slug: 'gratis-dessert-welgelegen',
      },
      {
        title: '15% korting op het terras',
        description: 'Geniet op ons verwarmde terras met 15% korting op de totaalrekening.',
        discountType: 'PERCENTAGE',
        discountValue: 15,
        terms: 'Geldig op het terras bij besteding van minimaal €25. Weersafhankelijk.',
        minimumPurchase: 25,
        maxClaims: 50,
        daysValid: 60,
        slug: 'terras-korting-welgelegen',
      },
    ],
  },
  {
    email: 'info@restaurantnectar.nl',
    ownerName: 'Joost van Outheusden',
    name: 'Restaurant Nectar',
    description: 'Modern Frans-Mediterraans restaurant in het centrum van Zutphen. Chef Joost kookt creatief en seizoensgebonden met verse producten uit de regio.',
    address: 'Nieuwstad 8',
    city: 'Zutphen',
    postalCode: '7201 NM',
    province: 'Gelderland',
    phone: '0575 482 000',
    website: 'https://restaurantnectar.nl',
    categories: ['restaurants'],
    vouchers: [
      {
        title: '€20 korting op 4-gangen dinermenu',
        description: 'Geniet van ons seizoensmenu voor €45 i.p.v. €65 p.p. (inclusief aperitief en koffie).',
        discountType: 'CASH',
        discountValue: 20,
        terms: 'Geldig op het 4-gangen seizoensmenu. Reserveren verplicht. Niet geldig op feestdagen.',
        minimumPurchase: 45,
        maxClaims: 25,
        daysValid: 60,
        slug: 'dinermenu-korting-nectar',
      },
      {
        title: 'Gratis fles huiswijn bij diner voor 2',
        description: 'Boek een tafel voor twee en ontvang een fles huiswijn cadeau bij het 4-gangen menu.',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis fles huiswijn (t.w.v. €25)',
        terms: 'Geldig bij het 4-gangen menu voor 2 personen. Reserveren verplicht.',
        minimumPurchase: 90,
        maxClaims: 20,
        daysValid: 90,
        slug: 'gratis-huiswijn-nectar',
      },
      {
        title: '25% korting op lunchmenu',
        description: 'Ontdek ons lunchmenu met 25% korting. Ideaal voor een culinaire pauze in Zutphen.',
        discountType: 'PERCENTAGE',
        discountValue: 25,
        terms: 'Geldig op het lunchmenu. Niet geldig op feestdagen.',
        maxClaims: 40,
        daysValid: 60,
        slug: 'lunch-korting-nectar',
      },
    ],
  },
]

// ─── BARS & CAFÉS ───────────────────────────────────────────

const bars: SeedBusiness[] = [
  {
    email: 'info@cafedekroongroenlo.nl',
    ownerName: 'Gerrit Willemsen',
    name: 'Café de Kroon',
    description: 'Authentieke bruine kroeg in het hart van Groenlo, al meer dan 100 jaar een begrip. Bekend om de 50 verschillende biersoorten van tap en fles, biljart en darts.',
    address: 'Notenboomstraat 46',
    city: 'Groenlo',
    postalCode: '7141 AD',
    province: 'Gelderland',
    phone: '0544 461 586',
    website: 'https://cafedekroongroenlo.nl',
    categories: ['bars'],
    vouchers: [
      {
        title: '2e speciaalbiertje gratis',
        description: 'Bestel een speciaalbiertje en ontvang het 2e gratis. Kies uit meer dan 50 soorten!',
        discountType: 'PRODUCT',
        discountDescription: '1 gratis speciaalbiertje (t.w.v. ~€4)',
        terms: 'Geldig op alle speciaalbieren. Per persoon maximaal 1 keer te gebruiken.',
        maxClaims: 100,
        daysValid: 90,
        slug: '2e-speciaalbiertje-gratis-de-kroon',
      },
      {
        title: '€5 korting op borrelplank voor 2',
        description: 'Gezellig borrelen? Ontvang €5 korting op onze borrelplank voor 2 personen.',
        discountType: 'CASH',
        discountValue: 5,
        terms: 'Geldig op de borrelplank voor 2 personen. Niet te combineren met andere acties.',
        maxClaims: 60,
        daysValid: 90,
        slug: 'borrelplank-korting-de-kroon',
      },
      {
        title: 'Gratis rondleiding Grolsch brouwerij',
        description: 'Ontvang een gratis toegangskaart voor de Grolsch brouwerij bij besteding van €15 in het café.',
        discountType: 'SERVICE',
        discountDescription: 'Gratis rondleiding Grolsch brouwerij (t.w.v. €12,50)',
        terms: 'Bij besteding van minimaal €15. Zolang de voorraad strekt.',
        minimumPurchase: 15,
        maxClaims: 30,
        daysValid: 90,
        slug: 'grolsch-rondleiding-de-kroon',
      },
    ],
  },
  {
    email: 'info@cafededeur.nl',
    ownerName: 'Bart de Groot',
    name: 'Café De Deur',
    description: 'Het gezelligste bruine café van Zutphen, sinds 1990 een vaste plek voor bierliefhebbers en muziekfans. Breed assortiment speciaalbieren en regelmatig live muziek.',
    address: 'Turfstraat 1',
    city: 'Zutphen',
    postalCode: '7201 KD',
    province: 'Gelderland',
    phone: '0575 518 181',
    website: 'https://cafededeur.nl',
    categories: ['bars'],
    vouchers: [
      {
        title: 'Gratis borrelapje bij 2 drankjes',
        description: 'Bestel 2 drankjes en ontvang een gratis borrelapje. Proost!',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis borrelapje (t.w.v. ~€3,50)',
        terms: 'Geldig bij bestelling van minimaal 2 drankjes.',
        maxClaims: 80,
        daysValid: 60,
        slug: 'gratis-borrelapje-de-deur',
      },
      {
        title: '2e Chamaven biertje gratis',
        description: 'Bestel een Chamaven craft bier en ontvang het 2e gratis. Lokaal gebrouwen in Zutphen!',
        discountType: 'PRODUCT',
        discountDescription: '1 gratis Chamaven bier (t.w.v. ~€4,50)',
        terms: 'Geldig op alle Chamaven bieren. Per persoon 1x te gebruiken.',
        maxClaims: 60,
        daysValid: 90,
        slug: 'chamaven-gratis-de-deur',
      },
      {
        title: '€3 korting op live muziek avond',
        description: 'Bezoek een live muziek avond en ontvang €3 korting op je eerste drankje.',
        discountType: 'CASH',
        discountValue: 3,
        terms: 'Geldig op avonden met live muziek. Zie onze agenda.',
        maxClaims: 80,
        daysValid: 60,
        slug: 'live-muziek-korting-de-deur',
      },
    ],
  },
  {
    email: 'info@stadsbasteon.nl',
    ownerName: 'Marco Jansen',
    name: "Eetcafé 't Stads-Basteon",
    description: 'Gezellig eetcafé in het centrum van Doetinchem. Bekend om de uitgebreide borrelkaart, spareribs en de populaire Burger Basteon.',
    address: 'Walstraat 60C',
    city: 'Doetinchem',
    postalCode: '7001 BV',
    province: 'Gelderland',
    phone: '0682 955 466',
    website: 'https://stadsbasteon.nl',
    categories: ['bars', 'restaurants'],
    vouchers: [
      {
        title: '2e hoofdgerecht halve prijs',
        description: 'Bestel 2 hoofdgerechten en ontvang het goedkoopste voor de halve prijs.',
        discountType: 'PERCENTAGE',
        discountValue: 50,
        terms: 'Korting geldt voor het goedkoopste hoofdgerecht. Niet te combineren met andere acties.',
        maxClaims: 50,
        daysValid: 60,
        slug: '2e-hoofdgerecht-halve-prijs-basteon',
      },
      {
        title: '€7,50 korting op luxe borrelarrangement',
        description: 'Ontvang €7,50 korting op ons luxe borrelarrangement voor 2 personen inclusief drankjes.',
        discountType: 'CASH',
        discountValue: 7.50,
        terms: 'Geldig op het luxe borrelarrangement voor 2 personen.',
        maxClaims: 40,
        daysValid: 90,
        slug: 'borrel-arrangement-basteon',
      },
      {
        title: 'Gratis nachos bij Burger Basteon',
        description: 'Bestel een Burger Basteon en ontvang een portie nachos gratis.',
        discountType: 'PRODUCT',
        discountDescription: 'Gratis nachos (t.w.v. €6,50)',
        terms: 'Geldig bij bestelling van een Burger Basteon.',
        maxClaims: 70,
        daysValid: 60,
        slug: 'gratis-nachos-basteon',
      },
    ],
  },
]

// ─── WELLNESS ───────────────────────────────────────────────

const wellness: SeedBusiness[] = [
  {
    email: 'info@debronsbergen.nl',
    ownerName: 'Annemarie Huisman',
    name: 'Wellness Center de Bronsbergen',
    description: 'Kleinschalig wellnesscentrum aan het Bronsbergenmeer bij Zutphen met 8 diverse sauna\'s, rustplekken en prachtig uitzicht. Bekend om de persoonlijke sfeer en professionele massages.',
    address: 'Bronsbergen 27',
    city: 'Zutphen',
    postalCode: '7207 AD',
    province: 'Gelderland',
    phone: '0575 519 200',
    website: 'https://debronsbergen.nl',
    categories: ['wellness'],
    vouchers: [
      {
        title: '20% korting op dagentree',
        description: 'Geniet van een dag ontspanning voor €30,80 i.p.v. €38,50. Inclusief toegang tot alle sauna\'s.',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        terms: 'Geldig op de reguliere dagentree. Niet geldig op feestdagen of in combinatie met andere acties.',
        maxClaims: 50,
        daysValid: 90,
        slug: 'dagentree-korting-bronsbergen',
      },
      {
        title: '€15 korting op hot stone massage',
        description: 'Boek een hot stone massage van 55 minuten voor €70 i.p.v. €85.',
        discountType: 'CASH',
        discountValue: 15,
        terms: 'Geldig op de hot stone massage 55 min. Reserveren verplicht.',
        minimumPurchase: 70,
        maxClaims: 30,
        daysValid: 90,
        slug: 'hot-stone-korting-bronsbergen',
      },
      {
        title: 'Dagentree + lunch voor €45',
        description: 'Combineer een dag sauna met een heerlijke lunch voor slechts €45 (normaal €52).',
        discountType: 'CASH',
        discountValue: 7,
        terms: 'Geldig op doordeweekse dagen. Inclusief lunch in het restaurant.',
        minimumPurchase: 45,
        maxClaims: 40,
        daysValid: 90,
        slug: 'dagentree-lunch-bronsbergen',
      },
    ],
  },
  {
    email: 'wellness@palestra.nl',
    ownerName: 'Linda van Dijk',
    name: 'Palestra Beauty & Wellness',
    description: 'Uitgebreid wellness- en saunacomplex op Landal Stroombroek met wereldse thema\'s: van Finse sauna tot Marokkaanse Berbertent en IJslands scrubhuis. Met verwarmd buitenzwembad.',
    address: 'Landweerswal 2',
    city: 'Braamt',
    postalCode: '7047 CE',
    province: 'Gelderland',
    phone: '0314 399 800',
    website: 'https://palestra.nl',
    categories: ['wellness'],
    vouchers: [
      {
        title: '€10 korting op dagentree',
        description: 'Dagentree voor €28,50 i.p.v. €38,50. Toegang tot alle sauna\'s en het verwarmde buitenbad.',
        discountType: 'CASH',
        discountValue: 10,
        terms: 'Geldig op de reguliere dagentree. Niet geldig op feestdagen. Leeftijd 16+.',
        maxClaims: 60,
        daysValid: 90,
        slug: 'dagentree-korting-palestra',
      },
      {
        title: 'Gratis ochtendboost bij massage',
        description: 'Boek een massage en ontvang gratis toegang tot de ochtendboost (09:45-12:00, t.w.v. €18).',
        discountType: 'SERVICE',
        discountDescription: 'Gratis ochtendboost (t.w.v. €18)',
        terms: 'Geldig bij boeking van een massage. Ochtendboost van 09:45 tot 12:00.',
        maxClaims: 40,
        daysValid: 60,
        slug: 'gratis-ochtendboost-palestra',
      },
      {
        title: '2 dagentrees voor de prijs van 1,5',
        description: 'Kom samen! 2 dagentrees voor €57,75 i.p.v. €77 (25% korting per persoon).',
        discountType: 'PERCENTAGE',
        discountValue: 25,
        terms: 'Geldig bij aankoop van 2 dagentrees tegelijk. Niet geldig op feestdagen.',
        maxClaims: 35,
        daysValid: 90,
        slug: 'duo-dagentree-palestra',
      },
    ],
  },
  {
    email: 'info@sensesbalimassage.nl',
    ownerName: 'Dewi Hartono',
    name: 'Senses Bali Massage',
    description: 'Intieme massagepraktijk in Winterswijk die Balinese massagetechnieken combineert met Lomi Lomi healing. Een weldaad voor lichaam en geest in de rust van de Achterhoek.',
    address: 'Vreehorstweg 47',
    city: 'Winterswijk',
    postalCode: '7109 BW',
    province: 'Gelderland',
    phone: '06 2417 9283',
    website: 'https://sensesbalimassage.nl',
    categories: ['wellness'],
    vouchers: [
      {
        title: '€10 korting op massage 60 min',
        description: 'Boek een Balinese massage van 60 minuten voor €35 i.p.v. €45.',
        discountType: 'CASH',
        discountValue: 10,
        terms: 'Geldig op de 60 minuten massage. Reserveren verplicht.',
        maxClaims: 30,
        daysValid: 90,
        slug: 'massage-korting-senses-bali',
      },
      {
        title: '15 min extra gratis bij 60 min massage',
        description: 'Boek een massage van 60 minuten en ontvang 15 minuten extra gratis. Wordt 75 min totaal!',
        discountType: 'SERVICE',
        discountDescription: '15 min extra massage gratis (t.w.v. €5)',
        terms: 'Geldig op de 60 minuten massage. Reserveren verplicht.',
        maxClaims: 25,
        daysValid: 90,
        slug: 'extra-tijd-senses-bali',
      },
      {
        title: 'Duo-massage: €15 korting',
        description: 'Boek een duo-massage (60 min) en ontvang €15 korting op het totaalbedrag.',
        discountType: 'CASH',
        discountValue: 15,
        terms: 'Geldig op duo-massages. Reserveren minimaal 2 dagen van tevoren.',
        minimumPurchase: 75,
        maxClaims: 20,
        daysValid: 120,
        slug: 'duo-massage-senses-bali',
      },
    ],
  },
]

// ─── ACCOMMODATIES ──────────────────────────────────────────

const accommodaties: SeedBusiness[] = [
  {
    email: 'info@hoevedewest.nl',
    ownerName: 'Marieke Scholten',
    name: 'B&B Hoeve De West',
    description: 'Luxe bed & breakfast voor volwassenen in het Achterhoekse coulisselandschap bij Winterswijk, met Finse sauna en uitgebreid ontbijt. Elke ochtend wakker worden met uitzicht op de weilanden.',
    address: 'Geelinkweg 10',
    city: 'Winterswijk',
    postalCode: '7119 AC',
    province: 'Gelderland',
    phone: '0543 530 200',
    website: 'https://www.hoevedewest.nl',
    categories: ['accommodaties'],
    vouchers: [
      {
        title: '3e nacht gratis',
        description: 'Boek 3 nachten en betaal er slechts 2. Inclusief ontbijt en uitzicht op de weilanden.',
        discountType: 'PERCENTAGE',
        discountValue: 33,
        terms: 'Geldig bij boeking van minimaal 3 nachten. Onder voorbehoud van beschikbaarheid.',
        maxClaims: 20,
        daysValid: 120,
        slug: '3e-nacht-gratis-hoeve-de-west',
      },
      {
        title: 'Gratis sauna-arrangement voor 2',
        description: 'Ontvang een gratis privé sauna-sessie voor 2 personen bij uw overnachting (t.w.v. €35).',
        discountType: 'SERVICE',
        discountDescription: 'Gratis sauna-arrangement (t.w.v. €35)',
        terms: 'Geldig bij overnachting van minimaal 2 nachten. Reserveren verplicht.',
        maxClaims: 25,
        daysValid: 120,
        slug: 'gratis-sauna-hoeve-de-west',
      },
      {
        title: 'Welkomstpakket met streekproducten',
        description: 'Ontvang bij aankomst een welkomstpakket met Achterhoekse streekproducten (t.w.v. €20).',
        discountType: 'PRODUCT',
        discountDescription: 'Welkomstpakket streekproducten (t.w.v. €20)',
        terms: 'Geldig bij overnachting van minimaal 2 nachten. Eén pakket per boeking.',
        maxClaims: 30,
        daysValid: 120,
        slug: 'welkomstpakket-hoeve-de-west',
      },
    ],
  },
  {
    email: 'info@hotelmondriaan.nl',
    ownerName: 'Rob Wesselink',
    name: 'Hotel Restaurant Mondriaan',
    description: 'Sfeervol hotel in een monumentaal pand aan de rand van Winterswijk met 20 kamers, restaurant en gratis parkeerplaats. Op loopafstand van het station en het centrum.',
    address: 'Misterweg 27',
    city: 'Winterswijk',
    postalCode: '7101 JB',
    province: 'Gelderland',
    phone: '0543 512 050',
    website: 'https://hotelrestaurantmondriaan.nl',
    categories: ['accommodaties', 'restaurants'],
    vouchers: [
      {
        title: '€25 korting op weekendverblijf',
        description: 'Ontvang €25 korting bij een verblijf van minimaal 2 nachten in het weekend.',
        discountType: 'CASH',
        discountValue: 25,
        terms: 'Geldig bij boeking van minimaal 2 nachten op vrijdag en/of zaterdag.',
        minimumPurchase: 150,
        maxClaims: 30,
        daysValid: 120,
        slug: 'weekend-korting-mondriaan',
      },
      {
        title: 'Gratis 3-gangen diner voor 2',
        description: 'Boek minimaal 2 nachten en ontvang een gratis 3-gangen diner in ons restaurant voor 2 personen.',
        discountType: 'SERVICE',
        discountDescription: 'Gratis diner voor 2 (t.w.v. ~€60)',
        terms: 'Geldig bij minimaal 2 nachten. Diner in eigen restaurant. Reserveren verplicht.',
        minimumPurchase: 200,
        maxClaims: 15,
        daysValid: 120,
        slug: 'gratis-diner-mondriaan',
      },
      {
        title: '10% korting op doordeweeks verblijf',
        description: 'Verblijf doordeweeks met 10% korting. Ideaal voor een rustige midweek break.',
        discountType: 'PERCENTAGE',
        discountValue: 10,
        terms: 'Geldig van zondag t/m donderdag. Niet te combineren met andere acties.',
        maxClaims: 40,
        daysValid: 90,
        slug: 'midweek-korting-mondriaan',
      },
    ],
  },
  {
    email: 'info@oetdoor.nl',
    ownerName: 'Thomas Brink',
    name: 'Oetdoor Glamping',
    description: 'Unieke Scandinavisch-geïnspireerde glamping in de Achterhoek met beltenten, Nordic Domes, tipi\'s en boshuisjes. Inclusief wilderness spa en gratis kano- en fietsverhuur.',
    address: 'Hogebrugweg 6',
    city: 'Haarlo',
    postalCode: '7273 PB',
    province: 'Gelderland',
    phone: '06 1234 5678',
    website: 'https://oetdoor.nl',
    categories: ['accommodaties', 'activiteiten'],
    vouchers: [
      {
        title: '2e nacht 50% korting',
        description: 'Boek een Nordic Dome of boshuisje en ontvang 50% korting op de 2e nacht.',
        discountType: 'PERCENTAGE',
        discountValue: 50,
        terms: 'Geldig op Nordic Domes en boshuisjes. Onder voorbehoud van beschikbaarheid.',
        maxClaims: 20,
        daysValid: 90,
        slug: '2e-nacht-korting-oetdoor',
      },
      {
        title: 'Gratis wilderness spa-sessie',
        description: 'Hottub + sauna voor 2 personen bij verblijf van minimaal 2 nachten (t.w.v. €40).',
        discountType: 'SERVICE',
        discountDescription: 'Gratis wilderness spa (t.w.v. €40)',
        terms: 'Geldig bij verblijf van minimaal 2 nachten.',
        maxClaims: 25,
        daysValid: 90,
        slug: 'gratis-spa-oetdoor',
      },
      {
        title: 'Gratis fietshuur voor 2 dagen',
        description: 'Verblijf minimaal 2 nachten en ontvang gratis fietshuur voor 2 dagen (t.w.v. €20).',
        discountType: 'PRODUCT',
        discountDescription: '2 dagen fietshuur gratis (t.w.v. €20)',
        terms: 'Geldig bij verblijf van minimaal 2 nachten. 2 fietsen, 2 dagen.',
        maxClaims: 30,
        daysValid: 120,
        slug: 'gratis-fietshuur-oetdoor',
      },
    ],
  },
]

// ─── ACTIVITEITEN ───────────────────────────────────────────

const activiteiten: SeedBusiness[] = [
  {
    email: 'info@klimbosruurlo.nl',
    ownerName: 'Erik Bosman',
    name: 'Klimbos Ruurlo',
    description: 'Het grootste klimbos van de Achterhoek met 9 parcoursen tot 20 meter hoogte, ziplines en een vrije val. Geschikt voor kinderen vanaf 6 jaar en volwassenen.',
    address: 'Hengeloseweg 2',
    city: 'Ruurlo',
    postalCode: '7261 LV',
    province: 'Gelderland',
    phone: '0573 451 200',
    website: 'https://klimbos.nl/locaties/ruurlo',
    categories: ['activiteiten'],
    vouchers: [
      {
        title: '2e persoon gratis bij klimbos',
        description: 'Koop 1 regulier ticket (€27,50) en krijg het 2e gratis. Samen klimmen is leuker!',
        discountType: 'PRODUCT',
        discountDescription: '2e ticket gratis (t.w.v. €27,50)',
        terms: 'Geldig op reguliere tickets (vanaf 1,40m). Niet geldig in vakanties en op feestdagen.',
        maxClaims: 40,
        daysValid: 90,
        slug: '2e-persoon-gratis-klimbos-ruurlo',
      },
      {
        title: '€5 korting op regulier ticket',
        description: 'Klim voor €22,50 i.p.v. €27,50. 3 uur klimmen inclusief instructie.',
        discountType: 'CASH',
        discountValue: 5,
        terms: 'Geldig op reguliere tickets (vanaf 1,40m). Niet geldig in schoolvakanties.',
        maxClaims: 80,
        daysValid: 90,
        slug: 'ticket-korting-klimbos-ruurlo',
      },
      {
        title: 'Gezinskorting: 20% op 4 tickets',
        description: 'Boek 4 tickets tegelijk en ontvang 20% korting. Perfect voor een gezinsuitje!',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        terms: 'Geldig bij aankoop van 4 tickets tegelijk. Combinatie junior + regulier toegestaan.',
        maxClaims: 30,
        daysValid: 90,
        slug: 'gezinskorting-klimbos-ruurlo',
      },
    ],
  },
  {
    email: 'info@kanoverhuuroost.nl',
    ownerName: 'Willem Hendriks',
    name: 'Kanoverhuur Oost',
    description: 'Kano-, kajak- en supverhuur op de mooiste rivieren van de Achterhoek. Vertrekpunten in Almen en Lochem, inclusief transport en instructie.',
    address: 'Deventerweg 67C',
    city: 'Laren',
    postalCode: '7245 PJ',
    province: 'Gelderland',
    phone: '0573 401 300',
    website: 'https://kanoverhuuroost.nl',
    categories: ['activiteiten'],
    vouchers: [
      {
        title: '€10 korting op kanotocht 3 uur',
        description: 'Huur een Canadese kano (max 3 pers.) voor €30 i.p.v. €40. Inclusief instructie en transport.',
        discountType: 'CASH',
        discountValue: 10,
        terms: 'Geldig op de 3-uurs kanotocht met Canadese kano. Reserveren verplicht.',
        maxClaims: 50,
        daysValid: 120,
        slug: 'kanotocht-korting-oost',
      },
      {
        title: '20% groepskorting bij 4+ boten',
        description: 'Boek 4 of meer boten en ontvang 20% korting op de totaalprijs. Perfect voor een dagje uit!',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        terms: 'Geldig bij boeking van 4 of meer boten. Reserveren verplicht.',
        maxClaims: 20,
        daysValid: 120,
        slug: 'groepskorting-kanoverhuur-oost',
      },
      {
        title: 'Gratis SUP-les bij kajakhuur',
        description: 'Huur een kajak en ontvang een gratis SUP-introductie les van 30 minuten.',
        discountType: 'SERVICE',
        discountDescription: 'Gratis SUP-les (t.w.v. €10)',
        terms: 'Geldig bij huur van een kajak voor minimaal 2 uur.',
        maxClaims: 35,
        daysValid: 120,
        slug: 'gratis-sup-les-oost',
      },
    ],
  },
  {
    email: 'info@oonkspeciaalzaak.nl',
    ownerName: 'Familie Oonk',
    name: 'Oonk Speciaalzaak — Fietsverhuur',
    description: 'Al meer dan 100 jaar de fietsverhuur van Winterswijk — Koninklijk Hofleverancier sinds 2019. Gewone fietsen, e-bikes, tandems en kinderfietsen voor het ontdekken van het Nationaal Landschap.',
    address: 'Misterstraat 47',
    city: 'Winterswijk',
    postalCode: '7101 ES',
    province: 'Gelderland',
    phone: '0543 512 367',
    website: 'https://oonkspeciaalzaak.nl',
    categories: ['activiteiten'],
    vouchers: [
      {
        title: 'Gratis e-bike upgrade',
        description: 'Boek een gewone fiets, krijg een e-bike. Moeiteloos door het Achterhoekse landschap! (t.w.v. €12/dag)',
        discountType: 'SERVICE',
        discountDescription: 'Gratis upgrade naar e-bike (t.w.v. €12)',
        terms: 'Geldig bij huur van minimaal 1 dag. Onder voorbehoud van beschikbaarheid.',
        maxClaims: 40,
        daysValid: 120,
        slug: 'gratis-ebike-upgrade-oonk',
      },
      {
        title: '2e dag fietshuur gratis',
        description: 'Huur een fiets of e-bike voor 1 dag en krijg de 2e dag gratis.',
        discountType: 'PRODUCT',
        discountDescription: '2e dag fietshuur gratis (t.w.v. €10-€22)',
        terms: 'Geldig op alle fietstypen. Retour uiterlijk 18:00 op de 2e dag.',
        maxClaims: 50,
        daysValid: 120,
        slug: '2e-dag-gratis-oonk',
      },
    ],
  },
]

// ─── EXPORT ALL ─────────────────────────────────────────────

export const achterhoekBusinesses: SeedBusiness[] = [
  ...restaurants,
  ...bars,
  ...wellness,
  ...accommodaties,
  ...activiteiten,
]
